# This file documents how to create the ACR secret for image pulls
# Run this after terraform apply to get ACR credentials:
#
# kubectl create secret docker-registry acr-secret \
#   --docker-server=<ACR_LOGIN_SERVER> \
#   --docker-username=<ACR_USERNAME> \
#   --docker-password=<ACR_PASSWORD> \
#   --namespace=bankx-app
#
# Example:
# kubectl create secret docker-registry acr-secret \
#   --docker-server=myacr.azurecr.io \
#   --docker-username=00000000-0000-0000-0000-000000000000 \
#   --docker-password=<ACR_PASSWORD> \
#   --namespace=bankx-app
